### ISSUE TITLE
Unable to open on brave browser

### ISSUE THREAD

**Issue by Adexbafo** [forkdelta/forkdelta.github.io#76] opened 2018-02-20 22:30 UTC
This site can't be opened on brave  browser, I don't know if this is a bug or deliberate intent. Please help review this on platform update. Thanks.

**Comment by freeatnet** [comment] 2018-02-20 22:39
Thanks for your report, @Adexbafo! We'll look into it shortly. Could you give us a bit more details on what's happening? Are you attempting to access forkdelta.github.io? Is the URL resolving for you? Does the initial interface load?

**Comment by freeatnet** [comment] 2018-02-20 22:46
I have confirmed that the website opens normally for me. More details would be appreciated so we can track this problem down.

**Comment by remedcu** [comment] 2018-02-21 17:04
This happened to me, I don't know if that is the same case for you. Do check it out though.

If you are using MetaMask
1. Ensure that you are logged in (logged in, not just installed)
2. If it is logged in, change your network from main network to test network. And after that, test network to main network.

The above usually works for me.

If you are importing Private Key, then try to remove that and re-enter the private key.

Let us know if this worked.

**Closed** 2018-03-06 19:22 UTC
